/*
 * Swagger Petstore
 *
 * A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// NewPet struct for NewPet
type NewPet struct {
	Name string `json:"name"`
	Tag *string `json:"tag,omitempty"`
}

// NewNewPet instantiates a new NewPet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewPet(name string) *NewPet {
	this := NewPet{}
	this.Name = name
	return &this
}

// NewNewPetWithDefaults instantiates a new NewPet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewPetWithDefaults() *NewPet {
	this := NewPet{}
	return &this
}

// GetName returns the Name field value
func (o *NewPet) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NewPet) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NewPet) SetName(v string) {
	o.Name = v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *NewPet) GetTag() string {
	if o == nil || o.Tag == nil {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewPet) GetTagOk() (*string, bool) {
	if o == nil || o.Tag == nil {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *NewPet) HasTag() bool {
	if o != nil && o.Tag != nil {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *NewPet) SetTag(v string) {
	o.Tag = &v
}

func (o NewPet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Tag != nil {
		toSerialize["tag"] = o.Tag
	}
	return json.Marshal(toSerialize)
}

type NullableNewPet struct {
	value *NewPet
	isSet bool
}

func (v NullableNewPet) Get() *NewPet {
	return v.value
}

func (v *NullableNewPet) Set(val *NewPet) {
	v.value = val
	v.isSet = true
}

func (v NullableNewPet) IsSet() bool {
	return v.isSet
}

func (v *NullableNewPet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewPet(val *NewPet) *NullableNewPet {
	return &NullableNewPet{value: val, isSet: true}
}

func (v NullableNewPet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewPet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


